apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
    - port: 2345
      name: default
      protocol: TCP
      targetPort: 3000
    - port: 80
      name: http
      protocol: TCP
      targetPort: 3000